name: SourceForge Commit

on:
  workflow_dispatch:
    inputs:
      sourceforge_url:
        description: "SourceForge download URL"
      tag_name:
        description: "Release tag name"

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download from SourceForge
        run: |
          wget ${{ github.event.inputs.sourceforge_url }}

      - name: Create Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: "*.zip"
          name: ${{ github.ref_name }}
          tag_name: ${{ github.ref }}
          body: |
            [sourceforge_url](${{ github.event.inputs.sourceforge_url }})
