name: SourceForge Backup

on:
  workflow_dispatch:
    inputs:
      SOURCEFORGE_URL:
        description: "SourceForge download URL"
        required: true
      RELEASE_NAME:
        description: "Release name"
        required: true
      TAG_NAME:
        description: "Release tag name"
        required: true

jobs:
  sourceforge_backup:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download from SourceForge
        run: |
          curl -LJO ${{ github.event.inputs.SOURCEFORGE_URL }}
          echo "ZIP_FILE=$(basename -a *.zip)" >> $GITHUB_ENV
          echo "ZIP_FILE_SHA256=$(sha256sum *.zip | cut -d' ' -f1)" >> $GITHUB_ENV

      - name: Create Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: "*.zip"
          name: ${{ github.event.inputs.RELEASE_NAME }}
          tag_name: ${{ github.event.inputs.TAG_NAME }}
          body: |
            Rom: [${{ env.ZIP_FILE }}](${{ github.event.inputs.SOURCEFORGE_URL }})
            SHA256: ${{ env.ZIP_FILE_SHA256 }}
