name: SourceForge Backup

on:
  workflow_dispatch:
    inputs:
      sourceforge_url:
        description: "SourceForge download URL"
      release_name:
        description: "Release name"
      tag_name:
        description: "Release tag name"

jobs:
  sourceforge_backup:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download from SourceForge
        run: |
          wget -q --show-progress ${{ github.event.inputs.sourceforge_url }}

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: "*.zip"
          name: ${{ github.event.inputs.release_name }}
          tag_name: ${{ github.event.inputs.tag_name }}
          body: |
            [SourceForge URL](${{ github.event.inputs.sourceforge_url }})
