name: SourceForge Backup

on:
  workflow_dispatch:
    inputs:
      SOURCEFORGE_FOLDER_URL:
        description: "SourceForge folder URL"
        required: true
      RELEASE_NAME:
        description: "Release name"
        required: true
      TAG_NAME:
        description: "Release tag name"
        required: true

jobs:
  sourceforge_backup:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Extract Download Links
        run: |
          HTML=$(curl -sL "${{ github.event.inputs.SOURCEFORGE_FOLDER_URL }}")
          DOWNLOAD_LINKS=$(echo "$HTML" | grep -oP 'href="[^"]+?/download"' | sed 's/href="//;s/"//')
          echo "DOWNLOAD_LINKS=$DOWNLOAD_LINKS" >> $GITHUB_ENV

      - name: Download from SourceForge
        run: |
          IFS=$'\n'
          for LINK in ${{ env.DOWNLOAD_LINKS }}; do
            FILE_NAME=$(basename "$LINK")
            curl -LJO "${{ github.event.inputs.SOURCEFORGE_FOLDER_URL }}/$LINK"
            echo "${FILE_NAME}: $(sha256sum "$FILE_NAME" | cut -d' ' -f1)" >> $GITHUB_ENV
          done

      - name: Create Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            ${{ env.FILE_NAME }}
          name: ${{ github.event.inputs.RELEASE_NAME }}
          tag_name: ${{ github.event.inputs.TAG_NAME }}
          body: |
            Files:
            ${{ env.FILE_NAME }}

